# Preface {.unnumbered}

Instead of just presenting the project in a normal quarto document, we chose another alternative. Namely, a quarto book. 

This enables us to provided all the necessary information, including the creation, joining and clearning pipeline, while keeping the official report clean.

## Use of Generative AI

Generative AI is a common and powerful tool. However, hallucination and illusion of competency prompte the user to use it with care.
In this project, we used ChatGPT at the earlier stage of the project to brainstorm ideas. In the later stage of the project, it was also used to check for the availability of R function for needed purposes and help us in overcoming bottleneck when programming.

Although a powerful tool, it shouldn't come at the cost of learning. Hence, a special emphasis was set in our group to avoid using it as much as possible. Whenever used, we tried to use in a way that it didn't digest and process the information in our place. Whether be it for declarative knowledge such statistical model and their assumption, economical theory or for procedural knowledge such as programming. Our goal was to left the thinking to us.

## Chapter of Choice

The **Chapter of Choice** is defined as the following: 

> In this chapter we want you to use a package that was not mentioned in the main part of the course (data manipulation, visualisation using ggplot2, regular expressions and reporting using Rmarkdown does not count) and perform a task that was not directly discussed in the course. Be creative!

Additionnaly, 

> It could even be a package that enables you to create prettier documents

As such, our chapter of choice is the whole project, written in a quarto-book. 
More than a simple project notebook or Rmarkdown file, quarto books allow for a clear structure and logic throughout the report. I allows for better compartementalization across files, treating each of them as independant entities. This is especially usefull in our case, since we want the code presentation and the report itself to have different presentation features.

On top of that, it comes with a crisp aesthetic out of the box.